---
# application tasks to be customized and to run after the main provision

- name: Set kernel storage path
  sudo: no
  lineinfile:
    dest=/home/vagrant/.profile
    line="export SYMFONY__kernel__storage_dir=\"/opt/symfony\""
    regexp="^export SYMFONY__kernel__storage_dir"
    state=present
    insertafter=EOF
    create=yes

- name: Set Composer install path
  sudo: no
  lineinfile:
    dest=/home/vagrant/.profile
    line="export COMPOSER_VENDOR_DIR=\"${SYMFONY__kernel__storage_dir}/vendor\""
    regexp="^export COMPOSER_VENDOR_DIR"
    state=present
    insertafter=EOF
    create=yes

- name: Create Symfony local directory
  sudo: yes
  file: path=/opt/symfony state=directory owner=vagrant group=vagrant recurse=true

- name: Install application dependencies
  sudo: no
  composer: command=install working_dir=/vagrant no_dev=no

- name: Migrate database and load fixtures
  sudo: no
  command: "{{ item }}"
  with_items:
    - php /vagrant/bin/console doctrine:migrations:migrate --no-interaction
    - php /vagrant/bin/console h:d:f:l --no-interaction

- name: Fix permissions
  sudo: yes
  file: path=/opt/symfony state=directory owner=vagrant group=vagrant recurse=true
