---
- name: Install xDebug
  apt: pkg=php{{ php.version }}-xdebug state=latest

- name: Install xDebug configuration
  template: src=xdebug.tpl dest=/etc/php/{{ php.version }}/mods-available/xdebug.ini owner=root group=root
