imports:
    - { resource: parameters.yml }
    - { resource: parameter_map.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: @SyliusCoreBundle/Resources/config/app/main.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    sylius.locale: "%locale%"

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.storage_dir%/var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - SyliusWebBundle:Common:forms.html.twig
            - SyliusResourceBundle::forms.html.twig
            - CmfMediaBundle:Form:fields.html.twig
    paths:
        %kernel.storage_dir%/vendor/payum/payum/src/Payum/Core/Resources/views: PayumCore
        %kernel.storage_dir%/vendor/payum/payum/src/Payum/Stripe/Resources/views: PayumStripe

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        ["SyliusWebBundle", "CmfCreateBundle", "SyliusResourceBundle"]
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.storage_dir%/vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        is_bundle: false
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
                dql:
                    string_functions:
                        MATCH: Sylius\Bundle\SearchBundle\Extension\Doctrine\MatchAgainstFunction

doctrine_phpcr:
    session:
        backend: %sylius.phpcr.backend%
        workspace: %sylius.phpcr.workspace%
        username: %sylius.phpcr.user%
        password: %sylius.phpcr.pass%
    odm:
        auto_mapping: true
        auto_generate_proxy_classes: %kernel.debug%

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Doctrine Migrations Configuration
#doctrine_migrations:
#    dir_name: "%kernel.root_dir%/migrations"
#    namespace: Application\Migrations
#    table_name: migration_versions
#    name: Application Migrations

# Lexik Maintenance Configuration
lexik_maintenance:
    authorized:
        ips: "%maintenance_ips%"
    driver:
        class: Lexik\Bundle\MaintenanceBundle\Drivers\FileDriver
        options:
            file_path: "%kernel.storage_dir%/var/cache/%kernel.environment%/maintenance_lock"

# Liip Monitor Configuration
liip_monitor:
    checks:
        security_advisory:
            lock_file: '%kernel.root_dir%/../composer.lock'
