---
- hosts: all
  sudo: true
  vars_files:
    - vars/all.yml
  roles:
    - server
    - vagrant_local
    - nginx
    - mysql
    - php
    - xdebug
    - composer
    - app
  environment:
    SYMFONY__kernel__storage_dir: /opt/symfony
    COMPOSER_VENDOR_DIR: /opt/symfony/vendor
