---
app:
    storage_path: /opt/symfony
server:
    install: '1'
    timezone: UTC
    locale: en_US.UTF-8
    packages: [git]
vagrant_local:
    install: '1'
    vm: { base_box: trusty64, hostname: symfony.dev, ip: 192.168.33.99, memory: '1024', sharedfolder: ./, syncType: nfs }
nginx:
    install: '1'
    docroot: /vagrant/web
    docindex: app_dev.php
    servername: symfony.dev
mysql:
    install: '1'
    root_password: ''
    database: symfony
    user: symfony
    password: symfony
    dump: ''
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-curl, php5-gd, php5-mysql]
xdebug:
    install: '1'
    idekey: PHPSTORM
composer:
    install: '1'
